apiVersion: apps/v1
kind: Deployment
metadata:
  name: alice-deployment
  labels:
    app: alice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alice 
  template:
    metadata:
      labels:
        app: alice 
    spec:
      containers:
      - name: mp-python
        image: irvnet/mp-python:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: alice-config
       

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: alice-config
data:
  PORT: "5000"
  SERVICE2_URL: "http://bob-service.default.svc.cluster.local:5000/polo"
  SERVICE3_URL: "http://chris-service.default.svc.cluster.local:5000/polo"

---

apiVersion: v1
kind: Service
metadata:
  labels:
  name: alice-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: alice
  type: NodePort
