apiVersion: apps/v1
kind: Deployment
metadata:
  name: bob-deployment
  labels:
    app: bob-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bob 
  template:
    metadata:
      labels:
        app: bob 
    spec:
      containers:
      - name: mp-python
        image: irvnet/mp-python:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: bob-config
       

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bob-config
data:
  PORT: "5000"
  SERVICE2_URL: "http://alice-service.default.svc.cluster.local:5000/polo"
  SERVICE3_URL: "http://chris-service.default.svc.cluster.local:5000/polo"


---

apiVersion: v1
kind: Service
metadata:
  labels:
  name: bob-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: bob
  type: NodePort
