apiVersion: apps/v1
kind: Deployment
metadata:
  name: chris-deployment
  labels:
    app: chris-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chris 
  template:
    metadata:
      labels:
        app: chris 
    spec:
      containers:
      - name: mp-python
        image: irvnet/mp-python:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: chris-config
       

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: chris-config
data:
  PORT: "5000"
  SERVICE2_URL: "http://service2:5000/marco"
  SERVICE3_URL: "http://service3:5200/marco"

---

apiVersion: v1
kind: Service
metadata:
  labels:
  name: chris-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: chris
  type: NodePort
